import Sidebar from "../components/Sidebar";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import { SessionProvider } from "../components/SessionProvider";
import Login from "../components/Login";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex text-sm">
              {/* Sidebar */}
              <div
                className="bg-slate-800 max-w-xs h-screen overflow-y-auto
            md:min-w-[20rem]"
              >
                <Sidebar />
              </div>

              {/* Client Provider - Notification */}

              <div className="bg-slate-700 flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
