import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* Sidebar */}

          {/* Client Provider - Notification */}

          <div className="bg-slate-700 flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
